### PR TITLE
remove the code behind the Manage crawls tab and UI

### LINKED ISSUE #29: was-registrar: don't use dor-fetcher service
dor-fetcher service is being phased out. Anywhere the code uses it, is there a diff way to get the info? If stumped, talk to Laney.

### LINKED ISSUE #30: disable manage-crawls tab
not used, and an easy way to avoid using dor-fetcher ...

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #29 and #30 by removing all the UI components for the "Manage crawls" tab, and all of the `/crawls` routes. 

We retain the data model and the `lib/` components for Crawl items, except for where `dor-fetcher` was used, as we must retain the functionality in `rake was_registrar:register_crawls`

Deployed to dev/stage for testing.

screen shot 2016-06-30 at 2 57 37 pm

screen shot 2016-06-30 at 3 27 59 pm

### CODE REVIEW

**Comment by ndushay** [comment]
I'm wondering:  is it better to 
a) do this wholesale removal (all code still avail from git history), or 
b) leave code in repo and take out routes and put in comments to the effect that it isn't used?

if a), should the commit message include something " ... about per request (see github issue #29 and #30)"

**Comment by drh-stanford** [comment]
ok i've changed the commit message to reference the github issues

**Comment by drh-stanford** [comment]
@ndushay i've created PR #32 as an alternative, which implements (b) in your comment above.

**Comment by drh-stanford** [comment]
will leave code in

**Pull request closed without merging**
